// <auto-generated />
namespace Bits_and_Bites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class movedingredientstorecipietable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movedingredientstorecipietable));
        
        string IMigrationMetadata.Id
        {
            get { return "201904051717379_moved ingredients to recipie table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
