// <auto-generated />
namespace Bits_and_Bites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dbconnection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbconnection));
        
        string IMigrationMetadata.Id
        {
            get { return "201904041915409_db connection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
