// <auto-generated />
namespace Bits_and_Bites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedimageclasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedimageclasses));
        
        string IMigrationMetadata.Id
        {
            get { return "201904090314585_updated image classes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
